# Generated by Django 5.0.6 on 2024-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_alter_producto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
