# Generated by Django 5.0.6 on 2024-06-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='cantidad_productos',
            field=models.IntegerField(default=0),
        ),
    ]
