# Generated by Django 5.0.6 on 2024-06-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('E', 'Enviado'), ('C', 'Camino'), ('R', 'Recibido'), ('N', 'No Recibido'), ('P', 'Preparacion')], default='P', max_length=1)),
                ('boleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagina.boleta')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina.region')),
            ],
        ),
    ]
