# Generated by Django 5.0.6 on 2024-06-30 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_rename_image_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='descripcion',
        ),
    ]
